global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'mariadb'
    static_configs:
      - targets: ['localhost:9104']

  - job_name: 'webapp'
    static_configs:
      - targets: ['localhost:5000']
